### ISSUE TITLE
CSS 实现元素垂直居中

### ISSUE THREAD

**Issue by yyman001** [yyman001/blog#25]
- 1 position:absolute
```css
//固定高宽
.absolute{
  position: absolute;
  width: 200px;
  height: 200px;
  top: 50%;
  left: 50%;
  margin-top: -100px;
  margin-left: -100px;
  background: red
}
//非固定高宽
.absolute2 {
  position: absolute;
  top: 0;
  right: 0;
  left: 0;
  bottom: 0;
  margin: auto; //关键
  background: red
}
```
- 2 display:table-cell //居中内容在盒子里面
缺点:不能与`float`一起适用,会失效;
解决办法:再套多一个容器用`float`
```css
 .table-cell{
   display: table-cell;
   vertical-align: middle;
   text-align: center;
   width: 120px;
   height: 120px;
   background: purple;
 }
```
- 3 line-height
缺点:需要固定高,block,inline-block 元素
```css
.line-height {
   width: 120px;
   height: 120px;
   line-height: 120px;
}
``` 
- 4 使用css3的新属性transform:translate(x,y)属性
缺点:不支持css3属性的浏览器不支持(IE)
```css
.translate {
  position: absolute;
  width: 80px;
  height: 80px;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  background: green;
}
```
- 5 伪类
缺点:需要多一个父容器元素
```css
.pseudo-class{
  position: fixed;
  display: block;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  text-align: center;
  background: rgba(0, 0, 0, .5);
}
.pseudo-class:before {
  content: '';
  display: inline-block;
  vertical-align: middle;
  height: 100%;
}
.pseudo-class .content {
  display: inline-block;
  vertical-align: middle;
  width: 60px;
  height: 60px;
  color: red;
  background: yellow;
}
```
