### ISSUE TITLE
谷歌浏览器57版不支持preventDefault事件解决方案

### ISSUE THREAD

**Issue by yyman001** [yyman001/blog#3]
新版谷歌的`preventDefault`事件会被阻挡,低版本没有问题,在需要的element元素上使用(需要拖动的element),不建议使用`*`会有问题的
解决:加上
```css
* { touch-action: none; }       //不建议
element { touch-action: none; } //建议
```
