### ISSUE TITLE
去掉Chrome 自动填充的表单背景色

### ISSUE THREAD

**Issue by yyman001** [yyman001/blog#47]
```css
input:-webkit-autofill {
    background-color: rgb(250, 255, 189);
    background-image: none;
    color: rgb(0, 0, 0);
   -webkit-box-shadow: 0 0 0px 1000px white inset;
}
```
https://segmentfault.com/q/1010000000671971
