### ISSUE TITLE
使用svg图标坑

### ISSUE THREAD

**Issue by yyman001** [yyman001/blog#55]
1.如果 父级元素嵌套了svg元素, 并且父级元素添加了事件,有可能会无法触发事件,所以需要一个伪类挡住svg图标
```scss
  .switch_action {
    position: relative;
    z-index: 9;
    /* 点击 svg 图层会导致 a 标签事件无法触发*/
    &:before {
      content: '';
      position: absolute;
      top: 0;
      right: 0;
      left: 0;
      bottom: 0;
    }
  }
```
